Cu 85ztudwc3 2 quiz screen ronisha shrestha
OttrTechnology/cancer-awareness-react pull request #2
Opened 2023-08-25 10:16 UTC by Ronishaaa

2023-08-25 10:16 UTC, rubek-joshi commented
Task linked: [CU-85ztudwc3 2. Quiz Screen](https://app.clickup.com/t/85ztudwc3)

2023-08-25 10:34 UTC, rubek-joshi requested changes

2023-08-25 10:34 UTC, rubek-joshi commented on src/styles/_typography.scss
>      // apply heading defaults below
Remove comment

2023-08-25 10:41 UTC, nirwan77 reviewed
fix the changes

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/Processed meat.svg
change file name to processed-meat

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/Chopstick.svg
change name to chopstick

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/TV.svg
change name to tv

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/bug spray.svg
change name to bug-spray

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/burnt meat.svg
change name to burnt-meat

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/diesel exhaust.svg
change name to diesel-exhaust

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/heat and freeze plastic.svg
change name to heat-and-freeze-plastic

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/high fat.svg
change name to high-fat

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/low physical.svg
change name to low-physical

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/red meat.svg
change name to red-meat

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/sleep deprived.svg
change name to sleep-deprived

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/uv radiation.svg
change name to uv-radiation

2023-08-25 10:41 UTC, nirwan77 commented on src/assets/questionImg/waxed apple.svg
change name to waxed-apple

2023-08-25 10:41 UTC, nirwan77 commented on src/screens/Quiz/Quiz.module.scss
> +  justify-content: space-between;
use justify between in apply

2023-08-25 10:41 UTC, nirwan77 commented on src/screens/Quiz/Quiz.module.scss
> +  width: 912px;
try not to use pixel

2023-08-25 10:41 UTC, nirwan77 commented on src/screens/Quiz/Result.module.scss
> +  padding: 72px 6rem 4rem 6rem;
try not to use pixel

2023-08-25 10:41 UTC, nirwan77 commented on src/screens/Quiz/Result.module.scss
> +  justify-content: center;
use flex and justify-center in apply

2023-08-25 10:41 UTC, nirwan77 commented on src/screens/Quiz/components/Lives.tsx
> +                fill={index < REMAINING_LIVES ? "#470FF4" : "#EDCDA6"}
import svg instead of using it directly and pass prop for ternary operator

2023-08-25 10:41 UTC, nirwan77 commented on src/styles/_spacing.scss
> +  width: 912px;
try not to use pixel

2023-08-28 05:03 UTC, nirwan77 approved these changes

2023-08-28 08:32 UTC, rubek-joshi requested changes

2023-08-28 08:32 UTC, rubek-joshi commented on src/screens/Quiz/Question.module.scss
> +  width: main.rem(912px);
use container-w class instead

2023-08-29 05:12 UTC, rubek-joshi approved these changes

2023-08-30 05:00 UTC, rubek-joshi approved these changes
Well done

2023-08-30 05:03 UTC, nirwan77 approved these changes

2023-08-30 05:04 UTC, merged