✨ Feat(#85ztre9m5): added lives logic
OttrTechnology/cancer-awareness-react pull request #3
Opened 2023-09-01 10:08 UTC by Ronishaaa

2023-09-01 10:08 UTC, rubek-joshi commented
Task linked: [CU-85ztre9m5 Game Logic](https://app.clickup.com/t/85ztre9m5)

2023-09-05 04:13 UTC, rubek-joshi requested changes

2023-09-05 04:13 UTC, rubek-joshi commented on src/context/GameContext.tsx
> +  answer: boolean;
src, answer, question, explanation should be nested

Something like this:
```ts
interface Quiz {
  question: string;
  answer: boolean
}

interface GameContextProps {
  highScore: number;
  currentQuestion: Quiz;
}
```

2023-09-05 04:13 UTC, rubek-joshi commented on src/context/GameContext.tsx
> +  handleOnClick: (currentScore: number) => void;
`handleOnClick` function name is too vague

2023-09-05 04:13 UTC, rubek-joshi commented on src/hooks/useGameContext.tsx
>  // TODO: implement useGameContext hook that also throws error if not used within provider
Remove comment

2023-09-05 04:13 UTC, rubek-joshi commented on src/main.tsx
> +import { GameContextProvider } from "context/GameContext.tsx";
import should be:
```ts
import { GameContextProvider } from "context";
```

2023-09-05 04:13 UTC, rubek-joshi commented on src/screens/Quiz/Question.tsx
> +import { useGameContext } from "hooks/useGameContext";
import should be:
```ts
import { useGameContext } from "hooks";
```

2023-09-05 04:13 UTC, rubek-joshi commented on src/screens/Quiz/components/Lives.tsx
> +import { useGameContext } from "hooks/useGameContext";
import should be:
```ts
import { useGameContext } from "hooks";
```

2023-09-05 04:13 UTC, rubek-joshi commented on src/screens/Quiz/components/Lives.tsx
> +  // const REMAINING_LIVES = remainingLives;
remove comment

2023-09-05 06:15 UTC, prakash-2021 requested changes

2023-09-05 06:15 UTC, prakash-2021 commented on src/context/GameContext.tsx
> +  //   const initialHighScore = highScoreString ? parseInt(highScoreString) : 0;
remove comments

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/GameOver/index.tsx
> +import { useGameContext } from "hooks/useGameContext";
import should not be like this

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/GameOver/index.tsx
> +    <div>
useless div 
use <></> instead

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/Quiz/Question.tsx
> +          <img className={styles.image} src={`/questionImg/${src}`} alt={src} />
alterantive text = src ?

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/Quiz/Result.tsx
> +import { useGameContext } from "hooks/useGameContext";
import same as above

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/Quiz/components/GameActions.tsx
> +import no from "assets/buttonIcon/no.svg";
import same as above

2023-09-05 06:15 UTC, prakash-2021 commented on src/screens/Quiz/components/GameActions.tsx
> +import { useGameContext } from "hooks/useGameContext";
import

2023-09-05 06:15 UTC, prakash-2021 commented on src/context/GameContext.tsx
> +  const handleOnClick = (currentScore: number) => {
rename to meaningful name

2023-09-07 07:41 UTC, rubek-joshi commented on src/components/Button.tsx
> +        label == "Next"
Don't use labels and values to set button styles

2023-09-07 07:41 UTC, rubek-joshi requested changes

2023-09-07 07:41 UTC, rubek-joshi commented on src/components/Button.tsx
> +        label == "Next"
Don't use labels and values to set button styles.

2023-09-08 06:31 UTC, merged