Cu 85ztre9hq 1 landing screen nirwan rai
OttrTechnology/cancer-awareness-react pull request #5
Opened 2023-09-07 09:59 UTC by nirwan77

made home page

2023-09-07 09:59 UTC, rubek-joshi commented
Task linked: [CU-85ztre9hq 1. Landing Screen](https://app.clickup.com/t/85ztre9hq)

2023-09-11 11:15 UTC, prakash-2021 requested changes

2023-09-11 11:15 UTC, prakash-2021 commented on src/screens/Home/index.module.scss
> +	@media only screen and (max-width: 600px) {
change it to global variable

2023-09-11 11:15 UTC, prakash-2021 commented on src/screens/Home/index.module.scss
> +		letter-spacing: -0.18px;
should be in em

2023-09-11 11:15 UTC, prakash-2021 commented on src/screens/Home/index.module.scss
> +		letter-spacing: -1.44px;
make letter spacing em for all

2023-09-11 11:15 UTC, prakash-2021 commented on src/screens/Home/index.tsx
> +                </a>
spacingsss

2023-09-11 11:15 UTC, prakash-2021 commented on src/styles/_layouts.scss
> +  // background-image: url("assets/backgroundPattern.svg");
remove unnecessary comments

2023-09-11 16:02 UTC, rubek-joshi requested changes

2023-09-12 09:56 UTC, prakash-2021 requested changes

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/GameOver/index.tsx
> +                  <div className="ca-heading--three ">
remove blank space

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Landing/index.module.scss
> +	// @media only screen and (max-width: main.$breakpoint-mobile) {
remove comment if you need later write it in comment

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Landing/index.module.scss
> +		letter-spacing: -0.18px;
letter spacing MUST be in em

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Landing/index.module.scss
> +
spacings ghin lagdo

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Landing/index.tsx
> +                  </a>
spacings

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Quiz/Result.tsx
> +              className=" ca-misc--link "
blank space

2023-09-12 09:56 UTC, prakash-2021 commented on src/screens/Quiz/components/GameActions.tsx
> +          <IconButton icon={<BiX />} onClick={() => handleAnswer(false)} />
use curry function if possible

2023-09-12 10:32 UTC, rubek-joshi approved these changes

2023-09-12 10:33 UTC, prakash-2021 approved these changes

2023-09-12 10:55 UTC, merged